//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITG.Brix.Teams.Application.Resources
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationFailures
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationFailures()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITG.Brix.Teams.Application.Resources.ValidationFailures", typeof(ValidationFailures).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Operator first name mandatory.
        /// </summary>
        public static string OperatorFirstNameMandatory
        {
            get
            {
                return ResourceManager.GetString("OperatorFirstNameMandatory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Operator id mandatory.
        /// </summary>
        public static string OperatorIdMandatory
        {
            get
            {
                return ResourceManager.GetString("OperatorIdMandatory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Operator last name mandatory.
        /// </summary>
        public static string OperatorLastNameMandatory
        {
            get
            {
                return ResourceManager.GetString("OperatorLastNameMandatory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Operator login mandatory.
        /// </summary>
        public static string OperatorLoginMandatory
        {
            get
            {
                return ResourceManager.GetString("OperatorLoginMandatory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Driver wait value is wrong. .
        /// </summary>
        public static string TeamDriverWaitWrongValue
        {
            get
            {
                return ResourceManager.GetString("TeamDriverWaitWrongValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Team name mandatory.
        /// </summary>
        public static string TeamNameMandatory
        {
            get
            {
                return ResourceManager.GetString("TeamNameMandatory", resourceCulture);
            }
        }
    }
}
